### ISSUE TITLE
Bug: Pressing spacebar

### ISSUE THREAD

**Issue by winkler1** [s-lugo/redux-tetris#1]
Hi-
 Nicely done! I'm used to having spacebar drop the current piece... but doing so starts a new game. The bug is then: arrow keys apply twice. The Left arrow moves a piece over twice, which makes the game much harder!
Thanks,
Jeff

**Comment by slugo** [comment]
Oh right, seems like I forgot to remove the space bar listener after it's used, space bar wasn't supposed to do anything inside the game. Will fix when I get home, thanks for the help!
