### ISSUE TITLE
Only half the page is not visible.

### ISSUE THREAD

**Issue by C-F-4** [s-lugo/redux-tetris#3]
Hey don't know if you're still working on this but I stumbled on the project form http://react.rocks page and there's an issue with screen sizes I guess.
The upper one is what I'm seeing(Clearly not showing the lower half of the game I'm guessing the scroll for the page is off, cropping up the page not fit into one screen).
The lower half is when I took a full page screenshot [using this.](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl)
![visibility_issue2](https://cloud.githubusercontent.com/assets/9998053/21287472/3e726f00-c492-11e6-8375-fa286506ada6.jpg)

**Comment by slugo** [comment]
Hi, thanks for spotting that. I fixed the scrollbar issue, but still, since I made the field size a fixed number to make the calculations easier, sometimes you won't see the entire field unless you scroll.

**Comment by C-F-4** [comment]
Glad you looked into it, @slugo But I still am seeing only half the canvas, and no way to scroll. It's about four blocks that are hidden.

**Comment by slugo** [comment]
Oh right, I forgot to build new bundle, will update demo page with latest when I get home, thanks.
